# Generated by Django 4.1.2 on 2022-10-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_reclamation_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamation',
            name='image',
        ),
        migrations.AddField(
            model_name='reclamation',
            name='nni',
            field=models.FileField(null=True, upload_to='nni/pdfs/'),
        ),
    ]
