# Generated by Django 4.1.2 on 2022-10-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_reclamation_image_reclamation_nni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamation',
            name='nni',
        ),
        migrations.AddField(
            model_name='reclamation',
            name='identity_card',
            field=models.FileField(null=True, upload_to='nni/'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='photo',
            field=models.FileField(null=True, upload_to='photo/'),
        ),
    ]
