# Generated by Django 4.1.2 on 2022-11-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_reclamation_description_alter_reclamation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='customer_phone_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
