# Generated by Django 4.1.2 on 2022-11-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_reclamation_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='identity_card',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
